allow = [
  "core/store::put",
  "core/store::get",
  "core/store::has",
  "core/refs::get",
  "core/refs::list",
  "core/refs::set",
  "core/refs::delete",
  "core/pkg-low::load-package",
  "core/pkg-low::snapshot",
  "core/gpk-low::export",
  "core/gpk-low::import"
]

[store]
dir = "./.genesis/store"

[refs]
path = "./.genesis/refs.gc"

[op."core/pkg-low::snapshot"]
base_dir = "."

[op."core/pkg-low::load-package"]
base_dir = "."

[op."core/gpk-low::export"]
base_dir = "."

[op."core/gpk-low::import"]
base_dir = "."
