use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn fail(msg: &str) -> ! {
    eprintln!("gc_prelude build script error: {msg}");
    std::process::exit(1);
}

fn read_to_string(path: &Path) -> String {
    match fs::read_to_string(path) {
        Ok(src) => src,
        Err(err) => fail(&format!("failed to read {}: {err}", path.display())),
    }
}

fn env_path(key: &str) -> PathBuf {
    match env::var(key) {
        Ok(value) => PathBuf::from(value),
        Err(err) => fail(&format!("missing env var {key}: {err}")),
    }
}

fn main() {
    let crate_dir = env_path("CARGO_MANIFEST_DIR");
    let repo_root = match crate_dir.parent().and_then(|p| p.parent()) {
        Some(path) => path.to_path_buf(),
        None => fail("gc_prelude should live under crates/<name>"),
    };
    let modules_dir = repo_root.join("prelude/modules");
    let manifest_path = modules_dir.join("manifest.toml");

    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let manifest_src = read_to_string(&manifest_path);
    let manifest: toml::Value = match toml::from_str(&manifest_src) {
        Ok(value) => value,
        Err(err) => fail(&format!(
            "failed to parse manifest {}: {err}",
            manifest_path.display()
        )),
    };

    let version = match manifest.get("version").and_then(|v| v.as_integer()) {
        Some(v) => v,
        None => fail(&format!(
            "{} must define integer `version`",
            manifest_path.display()
        )),
    };
    if version != 1 {
        fail(&format!(
            "{} has unsupported version {}; expected 1",
            manifest_path.display(),
            version
        ));
    }

    let modules = match manifest.get("modules").and_then(|v| v.as_array()) {
        Some(v) => v,
        None => fail(&format!(
            "{} must define `modules` array",
            manifest_path.display()
        )),
    };
    if modules.is_empty() {
        fail(&format!(
            "{} must list at least one module",
            manifest_path.display()
        ));
    }

    let mut assembled = String::new();
    for module in modules {
        let module_name = match module.as_str() {
            Some(name) => name,
            None => fail(&format!(
                "{} contains non-string module entry",
                manifest_path.display()
            )),
        };
        let module_path = modules_dir.join(module_name);
        println!("cargo:rerun-if-changed={}", module_path.display());
        let src = read_to_string(&module_path);
        assembled.push_str(&src);
        assembled.push('\n');
    }

    let out_dir = env_path("OUT_DIR");
    let generated = out_dir.join("prelude_assembled.rs");
    let out_src = format!(
        "// @generated by crates/gc_prelude/build.rs from prelude/modules/manifest.toml\n\
         pub const PRELUDE_SRC: &str = {:?};\n",
        assembled
    );
    if let Err(err) = fs::write(&generated, out_src) {
        fail(&format!("failed to write {}: {err}", generated.display()));
    }
}
