#!/usr/bin/env python3
"""Compute and verify content-addressed identities cited by ROADMAP.md."""

from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path
import re
import sys
from typing import Mapping, Sequence


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ROADMAP = ROOT / "ROADMAP.md"

COMMON_CAPABILITY_FILES = (
    "docs/spec/CAPABILITY_EVIDENCE_LEDGER_v0.1.schema.json",
    "docs/spec/CAPABILITY_EVIDENCE_LEDGER_v0.1.json",
    "scripts/lib/capability_ledger.py",
    "scripts/lib/roadmap_evidence.py",
    "scripts/check_capability_evidence_ledger.sh",
    "scripts/check_capability_evidence_ledger_contract.sh",
    "scripts/update_capability_status_views.sh",
    "feature_matrix.md",
    "docs/spec/FEATURE_MATRIX_EVIDENCE_v0.1.json",
    "docs/spec/FEATURE_MATRIX_EVIDENCE_v0.1.md",
    "docs/status/SELFHOST_AUTHORITY_v0.1.md",
    "docs/status/REDTEAM_REPORT.md",
)

VERSION_SURFACE_MANIFESTS = tuple(
    sorted(
        str(path.relative_to(ROOT))
        for base in (ROOT / "examples", ROOT / "tests")
        for path in base.rglob("package.toml")
    )
)

VERSION_SURFACE_CRATE_MANIFESTS = tuple(
    sorted(str(path.relative_to(ROOT)) for path in (ROOT / "crates").glob("*/Cargo.toml"))
)

CANONICAL_EXAMPLE_FILES = tuple(
    sorted(
        str(path.relative_to(ROOT))
        for path in (ROOT / "examples/canonical_language/v0.1").rglob("*")
        if path.is_file()
    )
)

TASK_BENCHMARK_FILES = tuple(
    sorted(
        str(path.relative_to(ROOT))
        for path in (ROOT / "benchmarks/agent_tasks/v0.1").rglob("*")
        if path.is_file()
    )
)

BUNDLES: Mapping[str, Sequence[str]] = {
    "capability-ledger-bundle": COMMON_CAPABILITY_FILES,
    "status-authority-bundle": COMMON_CAPABILITY_FILES
    + (
        "docs/status/SELFHOST_CUTOVER.md",
        "crates/gc_cli_driver/src/cmd_selfhost.rs",
        "scripts/check_selfhost_doc_runtime_parity.sh",
        "scripts/check_redteam_report.sh",
        "upgrade_plan.md",
        "docs/spec/SELFHOST_READINESS_SCORECARD_v0.1.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
    ),
    "root-lock-policy-bundle": (
        "scripts/check_root_lock_policy.sh",
        "genesis.workspace.toml",
        "genesis.lock",
    ),
    "roadmap-execution-contract-bundle": (
        "policies/roadmap_execution_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "docs/spec/ROADMAP_EXECUTION_MANIFEST_v0.1.schema.json",
        "scripts/lib/roadmap_execution_manifest.py",
        "scripts/check_roadmap_execution_manifest.sh",
        "scripts/update_roadmap_execution_manifest.sh",
        "scripts/lib/roadmap_evidence.py",
    ),
    "genesis-evidence-profile-bundle": (
        "docs/spec/ASSURANCE_ARTIFACTS_v0.1.md",
        "docs/spec/GENESIS_EVIDENCE_PREDICATE_v0.1.schema.json",
        "docs/spec/GENESIS_EVIDENCE_STATEMENT_v0.1.schema.json",
        "docs/spec/GENESIS_SLSA_BUILD_v1.schema.json",
        "docs/spec/GENESIS_EVIDENCE_BUNDLE_v0.1.schema.json",
        "docs/program/evidence/GENESIS_EVIDENCE_BUNDLE_v0.1.json",
        "scripts/lib/genesis_evidence_profile.py",
        "scripts/check_genesis_evidence_profile.sh",
        "scripts/update_genesis_evidence_profile.sh",
        "scripts/lib/roadmap_evidence.py",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "README.md",
    ),
    "genesis-evidence-verifier-bundle": (
        "tools/genesis-evidence-verifier/Cargo.toml",
        "tools/genesis-evidence-verifier/Cargo.lock",
        "tools/genesis-evidence-verifier/src/main.rs",
        "tools/genesis-evidence-verifier/src/json.rs",
        "tools/genesis-evidence-verifier/src/verify.rs",
        "docs/spec/GENESIS_EVIDENCE_TRUST_POLICY_v0.1.schema.json",
        "docs/spec/GENESIS_ARTIFACT_HASH_TREE_v0.1.schema.json",
        "docs/spec/GENESIS_EVIDENCE_VERIFIER_NEGATIVE_VECTORS_v0.1.schema.json",
        "policies/evidence_verifier_trust_v0.1.json",
        "docs/program/evidence/GENESIS_EVIDENCE_BUNDLE_v0.1.json",
        "docs/program/evidence/GENESIS_EVIDENCE_ARTIFACT_TREE_v0.1.json",
        "docs/program/evidence/GENESIS_EVIDENCE_VERIFIER_NEGATIVE_VECTORS_v0.1.json",
        "docs/program/evidence/artifact/genesis-example.bin",
        "scripts/lib/genesis_evidence_profile.py",
        "scripts/lib/genesis_evidence_verifier_vectors.py",
        "scripts/check_genesis_evidence_profile.sh",
        "scripts/check_genesis_evidence_verifier.sh",
        "scripts/update_genesis_evidence_verifier_vectors.sh",
        "docs/spec/ASSURANCE_ARTIFACTS_v0.1.md",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "evidence-storage-classes-bundle": (
        "policies/evidence_storage_classes_v0.1.json",
        "docs/spec/EVIDENCE_STORAGE_CLASSES_v0.1.schema.json",
        "docs/spec/EVIDENCE_FIXTURE_CLASSIFICATION_v0.1.schema.json",
        "docs/program/EVIDENCE_FIXTURE_CLASSIFICATION_v0.1.json",
        "scripts/lib/evidence_storage.py",
        "scripts/check_evidence_storage_classes.sh",
        "scripts/render_evidence_release_asset.sh",
        "scripts/update_evidence_fixture_classification.sh",
        "scripts/update_evidence_release_asset.sh",
        "tools/genesis-evidence-verifier/Cargo.toml",
        "tools/genesis-evidence-verifier/Cargo.lock",
        "tools/genesis-evidence-verifier/src/main.rs",
        "tools/genesis-evidence-verifier/src/json.rs",
        "tools/genesis-evidence-verifier/src/verify.rs",
        "policies/evidence_verifier_trust_v0.1.json",
        "docs/program/evidence/GENESIS_EVIDENCE_BUNDLE_v0.1.json",
        "docs/program/evidence/GENESIS_EVIDENCE_ARTIFACT_TREE_v0.1.json",
        "docs/program/evidence/artifact/genesis-example.bin",
        "docs/spec/ASSURANCE_ARTIFACTS_v0.1.md",
        "docs/spec/VERSIONING_v0.1.md",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "evidence-adversarial-matrix-bundle": (
        "docs/spec/EVIDENCE_ADVERSARIAL_MATRIX_v0.1.schema.json",
        "docs/program/EVIDENCE_ADVERSARIAL_MATRIX_v0.1.json",
        "docs/spec/GENESIS_EVIDENCE_TRUST_POLICY_v0.1.schema.json",
        "policies/evidence_verifier_trust_v0.1.json",
        "docs/spec/GENESIS_EVIDENCE_VERIFIER_NEGATIVE_VECTORS_v0.1.schema.json",
        "docs/program/evidence/GENESIS_EVIDENCE_VERIFIER_NEGATIVE_VECTORS_v0.1.json",
        "docs/program/EVIDENCE_FIXTURE_CLASSIFICATION_v0.1.json",
        "tools/genesis-evidence-verifier/src/json.rs",
        "tools/genesis-evidence-verifier/src/verify.rs",
        "scripts/lib/genesis_evidence_verifier_vectors.py",
        "scripts/check_genesis_evidence_verifier.sh",
        "scripts/check_evidence_adversarial_matrix.sh",
        "scripts/render_evidence_release_asset.sh",
        "crates/gc_effects/src/log.rs",
        "crates/gc_effects/src/runner.rs",
        "crates/gc_effects/src/tests.rs",
        "crates/gc_cli_driver/src/cmd_core.rs",
        "crates/gc_cli/tests/cli_run_replay_engine.rs",
        "crates/gc_wasi_cli/tests/cli_run_replay_engine.rs",
        "docs/spec/CLI.md",
        "docs/spec/GCLOG.md",
        "docs/spec/SEALS_DISPATCH_REPLAY.md",
        "docs/spec/ASSURANCE_ARTIFACTS_v0.1.md",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "prerequisite-manifest-bundle": (
        "genesis.prerequisites.json",
        "docs/spec/PREREQUISITES_v0.1.schema.json",
        "docs/spec/PREREQUISITES_v0.1.md",
        "scripts/lib/prerequisite_manifest.py",
        "scripts/genesis_prerequisites.sh",
        "scripts/check_prerequisite_manifest.sh",
        "rust-toolchain.toml",
        "package.json",
        "package-lock.json",
        ".github/workflows/ci.yml",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "policies/docs/doc_complexity_budget.toml",
        "docs/spec/DOC_COMPLEXITY_TARGETS_v0.1.md",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "dependency-mirror-bundle": (
        "genesis.dependency-mirror.json",
        "docs/spec/DEPENDENCY_MIRROR_v0.1.md",
        "docs/spec/DEPENDENCY_MIRROR_v0.1.schema.json",
        "docs/spec/DEPENDENCY_MIRROR_MANIFEST_v0.1.schema.json",
        "scripts/lib/dependency_mirror.py",
        "scripts/check_dependency_mirror_contract.sh",
        "scripts/update_dependency_mirror.sh",
        "scripts/test_offline_dependency_mirror.sh",
        ".github/workflows/ci.yml",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "policies/docs/doc_complexity_budget.toml",
        "docs/spec/DOC_COMPLEXITY_TARGETS_v0.1.md",
        "scripts/check_green_front_door.sh",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "version-surface-bundle": (
        "genesis.version-surfaces.json",
        "docs/spec/VERSION_SURFACES_v0.1.schema.json",
        "docs/spec/VERSION_SURFACES_v0.1.md",
        "Cargo.toml",
        "Cargo.lock",
        "crates/gc_cli_driver/src/cli_args.rs",
        "crates/gc_cli_driver/src/pkg_scaffold.rs",
        "crates/gc_cli_driver/src/selfhost_bridge.rs",
        "crates/gc_coreform/src/lib.rs",
        "crates/gc_coreform/src/term.rs",
        "crates/gc_kernel/src/compiled.rs",
        "crates/gc_kernel/src/compiled_blob.rs",
        "crates/gc_kernel/src/tests.rs",
        "crates/gc_kernel/src/value.rs",
        "crates/gc_effects/src/log.rs",
        "crates/gc_effects/src/runner.rs",
        "crates/gc_effects/src/runner_response_budget.rs",
        "crates/gc_effects/src/runner_cap_gc_gpk_low/gpk_ops.rs",
        "crates/gc_effects/src/tests.rs",
        "crates/gc_pkg/src/lib.rs",
        "crates/gc_pkg/src/manifest.rs",
        "crates/gc_pkg/src/workspace.rs",
        "crates/gc_pkg/src/lock.rs",
        "crates/gc_obligations/src/tests/mod.rs",
        "crates/gc_prelude/src/prelude_contract_effect.rs",
        "crates/gc_prelude/src/selfhost_coreform_v1.rs",
        "crates/gc_prelude/src/selfhost_compiled_cache.rs",
        "crates/gc_vcs/src/lib.rs",
        "crates/gc_vcs/src/gpk.rs",
        "crates/gc_vcs/src/schema.rs",
        "crates/gc_vcs/src/signing.rs",
        "crates/gc_wasm/src/runtime.rs",
        "crates/gc_cli/tests/cli_pkg_gpk.rs",
        "crates/gc_cli/tests/cli_vcs_blame_why.rs",
        "selfhost/toolchain.gc",
        "scripts/lib/version_surfaces.py",
        "scripts/check_version_surfaces.sh",
        "scripts/check_versioning_release_hygiene.sh",
        "scripts/check_release_smoke.sh",
        "scripts/check_green_front_door.sh",
        "docs/spec/VERSIONING_v0.1.md",
        "docs/spec/RELEASE_SMOKE_v0.1.md",
        "docs/spec/PACKAGE_TOML.md",
        "docs/spec/GCLOG.md",
        "docs/spec/GCLOG_SCHEMA.md",
        "docs/spec/VALUE_EFFECT_HASH.md",
        "docs/DEPRECATION_MAP_v0.1.md",
        "CHANGELOG.md",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    )
    + VERSION_SURFACE_CRATE_MANIFESTS
    + VERSION_SURFACE_MANIFESTS,
    "v1-compatibility-registry-bundle": (
        "genesis.compatibility.json",
        "docs/spec/V1_COMPATIBILITY_REGISTRY_v0.1.schema.json",
        "docs/spec/VERSION_SURFACES_v0.1.md",
        "scripts/lib/v1_compatibility.py",
        "scripts/check_v1_compatibility.sh",
        "crates/gc_coreform/src/lib.rs",
        "crates/gc_coreform/src/term.rs",
        "crates/gc_kernel/src/lib.rs",
        "crates/gc_kernel/src/value.rs",
        "crates/gc_effects/src/lib.rs",
        "crates/gc_effects/src/log.rs",
        "crates/gc_pkg/src/lib.rs",
        "crates/gc_patches/src/lib.rs",
        "crates/gc_patches/src/patch_parse.rs",
        "crates/gc_patches/src/patch_apply.rs",
        "crates/gc_vcs/src/lib.rs",
        "crates/gc_vcs/src/patch.rs",
        "crates/gc_vcs/src/snapshot.rs",
        "crates/gc_prelude/src/lib.rs",
        "crates/gc_prelude/src/selfhost_coreform_v1.rs",
        "crates/gc_cli_driver/src/cmd_selfhost_artifact.rs",
        "scripts/lib/genesis_evidence_profile.py",
        "scripts/check_green_front_door.sh",
        "scripts/check_versioning_release_hygiene.sh",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        ".github/workflows/ci.yml",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gate-manifest-bundle": (
        "policies/gates_v0.1.json",
        "docs/spec/GATE_MANIFEST_v0.1.schema.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "scripts/lib/gate_manifest.py",
        "scripts/check_gate_manifest.sh",
        "scripts/update_gate_manifest.sh",
        "genesis.prerequisites.json",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gate-resource-telemetry-bundle": (
        "policies/gate_telemetry_v0.1.json",
        "docs/spec/GATE_RESOURCE_TELEMETRY_v0.1.schema.json",
        "scripts/lib/gate_telemetry.py",
        "scripts/lib/gate_telemetry.sh",
        "scripts/check_gate_resource_telemetry.sh",
    ),
    "deterministic-cleanup-bundle": (
        "policies/deterministic_cleanup_v0.1.json",
        "docs/spec/DETERMINISTIC_CLEANUP_POLICY_v0.1.schema.json",
        "docs/spec/DETERMINISTIC_CLEANUP_MARKER_v0.1.schema.json",
        "docs/spec/DETERMINISTIC_CLEANUP_PLAN_v0.1.schema.json",
        "docs/spec/DETERMINISTIC_CLEANUP_RESULT_v0.1.schema.json",
        "scripts/lib/deterministic_cleanup.py",
        "scripts/reclaim_build_space.sh",
        "scripts/lib/cargo_cache.py",
        "scripts/lib/dependency_mirror.py",
        "scripts/check_deterministic_cleanup.sh",
    ),
    "generated-state-lifecycle-bundle": (
        "policies/generated_state_v0.1.json",
        "docs/spec/GENERATED_STATE_POLICY_v0.1.schema.json",
        "docs/spec/GENERATED_STATE_REGISTRY_v0.1.schema.json",
        "docs/spec/DETERMINISTIC_CLEANUP_PLAN_v0.1.schema.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "scripts/lib/generated_state.py",
        "scripts/lib/deterministic_cleanup.py",
        "scripts/lib/cargo_cache.py",
        "scripts/lib/cargo_target_dir.sh",
        "scripts/check_deterministic_cleanup.sh",
        "scripts/render_cargo_target_dir_policy_report.sh",
        "scripts/check_cargo_target_dir_policy.sh",
        "scripts/check_evidence_storage_classes.sh",
        "scripts/render_evidence_release_asset.sh",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "governance-consolidation-bundle": (
        "policies/gates_v0.1.json",
        "docs/spec/GATE_MANIFEST_v0.1.schema.json",
        "scripts/lib/gate_manifest.py",
        "scripts/check_gate_manifest.sh",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "scripts/render_upgrade_plan_health_report.sh",
        "scripts/check_capability_evidence_ledger.sh",
        "scripts/update_capability_status_views.sh",
        "scripts/lib/roadmap_evidence.py",
    ),
    "engineering-gate-budget-bundle": (
        "policies/engineering_gate_budgets_v0.1.json",
        "docs/spec/ENGINEERING_GATE_BUDGETS_v0.1.schema.json",
        "scripts/lib/engineering_gate_budgets.py",
        "scripts/check_engineering_gate_contract.sh",
        "policies/gates_v0.1.json",
        "policies/gate_telemetry_v0.1.json",
        "scripts/lib/gate_telemetry.py",
        "scripts/lib/gate_telemetry.sh",
        "scripts/check_gate_resource_telemetry.sh",
        "scripts/test_changed_fast.sh",
        "scripts/render_upgrade_plan_health_report.sh",
        "policies/deterministic_cleanup_v0.1.json",
        "policies/source_decomposition_progress.toml",
        "genesis.prerequisites.json",
        "scripts/lib/panic_policy.py",
        "scripts/check_no_user_panics.sh",
        "scripts/check_no_user_panics_compiler.sh",
        "scripts/verify_prebuilt_evidence_bundle.sh",
        "scripts/lib/prebuilt_evidence_verify.py",
        "scripts/lib/toml_compat.py",
        "scripts/lib/vendor/tomli/LICENSE",
        "scripts/lib/vendor/tomli/__init__.py",
        "scripts/lib/vendor/tomli/_parser.py",
        "scripts/lib/vendor/tomli/_re.py",
        "scripts/lib/vendor/tomli/_types.py",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
    ),
    "reference-host-profile-bundle": (
        "policies/reference_host_profiles_v0.1.json",
        "docs/spec/REFERENCE_HOST_PROFILES_v0.1.schema.json",
        "docs/spec/REFERENCE_HOST_OBSERVATION_v0.1.schema.json",
        "scripts/lib/reference_host_profiles.py",
        "scripts/render_reference_host_observation.sh",
        "scripts/check_reference_host_profiles.sh",
        "genesis.prerequisites.json",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "roadmap-workload-bundle": (
        "policies/perf/roadmap_workloads_v0.1.json",
        "docs/spec/ROADMAP_WORKLOADS_v0.1.schema.json",
        "scripts/lib/roadmap_workloads.py",
        "scripts/check_roadmap_workloads.sh",
        "benchmarks/roadmap/v0.1/pb1_fib_25.gc",
        "benchmarks/roadmap/v0.1/pb4_vector_1000000.gc",
        "benchmarks/roadmap/v0.1/pb5_map_100000.gc",
        "benchmarks/roadmap/v0.1/pb6_trivial_check.gc",
        "benchmarks/roadmap/v0.1/pb8_warm_request.jsonl",
        "benchmarks/roadmap/v0.1/pb9_semantic_parity_corpus.json",
        "benchmarks/roadmap/v0.1/pb10_bootstrap_inputs.json",
        "selfhost/parse.gc",
        "prelude/prelude.gc",
        "tests/spec/coreform/app_sugar.in.gc",
        "tests/spec/coreform/map_order.in.gc",
        "tests/spec/pkg_fail_budgets/budget.gc",
        "tests/spec/pkg_fail_determinism/fail.gc",
        "selfhost/toolchain.gc",
        "selfhost/toolchain_manifest.gc",
        "policies/reference_host_profiles_v0.1.json",
        "policies/gates_v0.1.json",
        "scripts/lib/gate_manifest.py",
        "scripts/check_gate_manifest.sh",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "roadmap-baseline-bundle": (
        "docs/spec/ROADMAP_BASELINE_STATEMENT_v0.1.schema.json",
        "docs/spec/ROADMAP_BASELINE_BUNDLE_v0.1.schema.json",
        "docs/program/evidence/roadmap-baselines/roadmap-baseline-e0-2026-07-10-sha256-a3d6c7b809f1c1ba403bab0c4e18fce94154cbae4b35b23aa9e96cfb1c02e967.json",
        "docs/program/evidence/roadmap-baselines/roadmap-baseline-fixture-key-sha256-f942d973dd550ff9b95e0a61f47e8cee9580e8bb8d43f0226408d57bde2d113f.pub",
        "scripts/lib/roadmap_baseline.py",
        "scripts/check_roadmap_baseline.sh",
        "scripts/update_roadmap_baseline.sh",
        "crates/gc_runtime_bench/src/config.rs",
        "crates/gc_runtime_bench/src/main.rs",
        "crates/gc_runtime_bench/src/bench_workloads.rs",
        "crates/gc_runtime_bench/Cargo.toml",
        "tools/genesis-evidence-producer/Cargo.toml",
        "tools/genesis-evidence-producer/Cargo.lock",
        "tools/genesis-evidence-producer/src/main.rs",
        "tools/genesis-evidence-verifier/Cargo.toml",
        "tools/genesis-evidence-verifier/Cargo.lock",
        "tools/genesis-evidence-verifier/src/json.rs",
        "tools/genesis-evidence-verifier/src/bin/genesis-roadmap-baseline-verifier.rs",
        "scripts/check_genesis_evidence_verifier.sh",
        "policies/perf/roadmap_workloads_v0.1.json",
        "policies/reference_host_profiles_v0.1.json",
        "policies/evidence_storage_classes_v0.1.json",
        "docs/program/EVIDENCE_FIXTURE_CLASSIFICATION_v0.1.json",
        "scripts/lib/evidence_storage.py",
        "scripts/check_evidence_storage_classes.sh",
        "scripts/update_evidence_fixture_classification.sh",
        "policies/gates_v0.1.json",
        "scripts/lib/gate_manifest.py",
        "scripts/check_gate_manifest.sh",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "release-notes-bundle": (
        "policies/release_notes_v0.1.json",
        "docs/spec/RELEASE_NOTES_POLICY_v0.1.schema.json",
        "docs/spec/RELEASE_NOTES_v0.1.schema.json",
        "docs/program/RELEASE_NOTES_v0.2.0.json",
        "CHANGELOG.md",
        "scripts/lib/release_notes.py",
        "scripts/check_release_notes.sh",
        "scripts/update_release_notes.sh",
        "scripts/check_release_smoke.sh",
        "docs/spec/RELEASE_SMOKE_v0.1.md",
        "docs/spec/VERSIONING_v0.1.md",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "policies/gates_v0.1.json",
        "scripts/lib/gate_manifest.py",
        "scripts/check_gate_manifest.sh",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gc-agent-profile-bundle": (
        "policies/gc_agent_profile_v0.3.json",
        "docs/spec/GC_AGENT_PROFILE_v0.3.schema.json",
        "docs/spec/GC_AGENT_PROFILE_v0.3.json",
        "scripts/lib/gc_agent_profile.py",
        "scripts/check_gc_agent_profile.sh",
        "scripts/update_gc_agent_profile.sh",
        "crates/gc_cli/tests/gc_agent_profile_v03.rs",
        "crates/gc_cli/Cargo.toml",
        "Cargo.lock",
        "genesis.version-surfaces.json",
        "genesis.compatibility.json",
        "crates/gc_coreform/src/lib.rs",
        "crates/gc_coreform/src/term.rs",
        "crates/gc_kernel/src/eval.rs",
        "crates/gc_kernel/src/eval_forms.rs",
        "crates/gc_kernel/src/eval_prims.rs",
        "crates/gc_kernel/src/value.rs",
        "crates/gc_kernel/src/tests.rs",
        "crates/gc_pkg/src/manifest.rs",
        "crates/gc_pkg/src/workspace.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/AGENT_ONBOARDING_v0.1.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "docs/spec/WRITE_GENESISCODE_SKILL_v0.1.json",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.json",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.md",
        "scripts/check_genesiscode_authoring_skill.sh",
        "scripts/check_write_genesiscode_skill_guide.sh",
        "scripts/check_write_genesiscode_skill_pack.sh",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "policies/gates_v0.1.json",
        "scripts/lib/gate_manifest.py",
        "scripts/check_gate_manifest.sh",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        "README.md",
        "scripts/check_capability_evidence_ledger_contract.sh",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gc-agent-core-card-bundle": (
        "policies/gc_agent_core_card_v0.3.json",
        "docs/spec/GC_AGENT_CORE_CARD_v0.3.md",
        "docs/spec/GC_AGENT_CORE_CARD_v0.3.json",
        "docs/spec/GC_AGENT_PROFILE_v0.3.json",
        "docs/spec/GC_AGENT_PROFILE_v0.3.schema.json",
        "scripts/lib/gc_agent_core_card.py",
        "scripts/check_gc_agent_core_card.sh",
        "scripts/update_gc_agent_core_card.sh",
        "crates/gc_cli/tests/gc_agent_profile_v03.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/AGENT_ONBOARDING_v0.1.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "docs/spec/WRITE_GENESISCODE_SKILL_v0.1.json",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.json",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.md",
        "scripts/check_write_genesiscode_skill_guide.sh",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "policies/gates_v0.1.json",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        ".github/workflows/ci.yml",
        "policies/docs/doc_complexity_budget.toml",
        "docs/spec/DOC_COMPLEXITY_TARGETS_v0.1.md",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "README.md",
        "scripts/check_capability_evidence_ledger_contract.sh",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gc-agent-corpus-bundle": (
        "docs/spec/GC_AGENT_CORPUS_v0.1.schema.json",
        "docs/spec/GC_AGENT_CORPUS_v0.1.json",
        "scripts/lib/gc_agent_corpus.py",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "docs/spec/GC_AGENT_PROFILE_v0.3.json",
        "benchmarks/diagnostics/repair_utility/v0.1/workloads.json",
        "benchmarks/roadmap/v0.1/pb9_semantic_parity_corpus.json",
        "examples/effects_demo/caps.toml",
        "examples/effects_demo/data.txt",
        "examples/effects_demo/read.gc",
        "examples/gfx_demos/hybrid_web.gc",
        "examples/gfx_demos/scene3d.gc",
        "examples/gfx_demos/ui_app.gc",
        "examples/hello_pkg/caps.toml",
        "examples/hello_pkg/hello.gc",
        "examples/hello_pkg/package.toml",
        "scripts/check_cli_diagnostics_contract.sh",
        "scripts/check_docs_quickstart.sh",
        "scripts/check_roadmap_workloads.sh",
        "docs/INDEX.md",
        "llms.txt",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gc-canonical-examples-bundle": (
        "docs/spec/GC_CANONICAL_EXAMPLES_v0.1.schema.json",
        "scripts/lib/gc_canonical_examples.py",
        "crates/gc_cli/tests/cli_canonical_language_examples.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/spec/GC_AGENT_CORPUS_v0.1.json",
        "docs/spec/GC_AGENT_PROFILE_v0.3.json",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/AGENT_ONBOARDING_v0.1.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "docs/INDEX.md",
        "README.md",
        "scripts/lib/roadmap_evidence.py",
    )
    + CANONICAL_EXAMPLE_FILES,
    "gc-agent-task-benchmark-bundle": (
        "docs/spec/GC_AGENT_TASK_BENCHMARK_v0.1.schema.json",
        "scripts/lib/gc_task_benchmarks.py",
        "crates/gc_cli/tests/cli_agent_task_benchmarks.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/spec/GC_AGENT_CORPUS_v0.1.json",
        "docs/spec/GC_AGENT_PROFILE_v0.3.json",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/AGENT_ONBOARDING_v0.1.md",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.md",
        "docs/INDEX.md",
        "llms.txt",
        "_quarto.yml",
        "scripts/render_quarto_reference.py",
        "scripts/lib/roadmap_evidence.py",
    )
    + TASK_BENCHMARK_FILES,
    "gc-agent-benchmark-scoring-bundle": (
        "docs/spec/GC_AGENT_BENCHMARK_SCORING_v0.1.json",
        "docs/spec/GC_AGENT_BENCHMARK_SCORING_v0.1.schema.json",
        "docs/spec/GC_AGENT_BENCHMARK_SCORE_v0.1.schema.json",
        "scripts/lib/gc_agent_scoring.py",
        "scripts/lib/gc_agent_scoring_contract.py",
        "crates/gc_cli/tests/cli_agent_benchmark_scoring.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/spec/GC_AGENT_CORPUS_v0.1.json",
        "docs/spec/GC_AGENT_PROFILE_v0.3.json",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/AGENT_ONBOARDING_v0.1.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.md",
        "docs/INDEX.md",
        "llms.txt",
        "scripts/render_quarto_reference.py",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gc-agent-benchmark-run-bundle": (
        "docs/spec/GC_AGENT_BENCHMARK_RUN_v0.1.schema.json",
        "docs/spec/GC_AGENT_MODEL_RUNNER_EFFECT_v0.1.json",
        "scripts/lib/gc_agent_benchmark_run.py",
        "scripts/lib/gc_agent_scoring.py",
        "scripts/lib/gc_agent_scoring_contract.py",
        "docs/spec/GC_AGENT_BENCHMARK_SCORING_v0.1.json",
        "crates/gc_cli/tests/cli_agent_benchmark_run.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "examples/agent_benchmark_reproducibility/candidate/main.gc",
        "examples/agent_benchmark_reproducibility/candidate/requirements.md",
        "examples/agent_benchmark_reproducibility/caps.toml",
        "examples/agent_benchmark_reproducibility/invocation/model-output.txt",
        "examples/agent_benchmark_reproducibility/invocation/request.json",
        "examples/agent_benchmark_reproducibility/invocation/response.json",
        "examples/agent_benchmark_reproducibility/model-effect.gclog",
        "examples/agent_benchmark_reproducibility/model_effect.gc",
        "examples/agent_benchmark_reproducibility/models/tokenizer.json",
        "examples/agent_benchmark_reproducibility/models/weights.fixture",
        "examples/agent_benchmark_reproducibility/prompts/system.md",
        "examples/agent_benchmark_reproducibility/prompts/user.md",
        "examples/agent_benchmark_reproducibility/run.json",
        "examples/agent_benchmark_reproducibility/score.json",
        "examples/agent_benchmark_reproducibility/scaffold-manifest.json",
        "examples/agent_benchmark_reproducibility/tool-transcript.jsonl",
        "examples/agent_benchmark_reproducibility/tools/catalog.json",
        "examples/agent_benchmark_reproducibility/tools/local_model_bridge.py",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/spec/GC_AGENT_CORPUS_v0.1.json",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/AGENT_ONBOARDING_v0.1.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.md",
        "docs/INDEX.md",
        "llms.txt",
        "scripts/render_quarto_reference.py",
        "scripts/lib/roadmap_evidence.py",
    ),
    "genesisbench-protocol-bundle": (
        "docs/spec/GENESISBENCH_PROTOCOL_v0.1.json",
        "docs/spec/GENESISBENCH_PROTOCOL_v0.1.schema.json",
        "docs/spec/GENESISBENCH_ELIGIBILITY_v0.1.schema.json",
        "docs/spec/GENESISBENCH_CONTAMINATION_ATTESTATION_v0.1.schema.json",
        "docs/spec/GENESISBENCH_ADAPTATION_MANIFEST_v0.1.schema.json",
        "docs/spec/GENESISBENCH_HARDWARE_EVIDENCE_v0.1.schema.json",
        "docs/spec/GENESISBENCH_SCAFFOLD_MANIFEST_v0.1.schema.json",
        "scripts/lib/genesisbench_protocol.py",
        "scripts/lib/genesisbench_protocol_contract.py",
        "scripts/lib/genesisbench_contamination.py",
        "scripts/lib/genesisbench_protocol_run.py",
        "scripts/lib/genesisbench_tracks.py",
        "scripts/lib/genesisbench_eligibility.py",
        "scripts/lib/genesisbench_analysis.py",
        "docs/spec/GENESISBENCH_ANALYSIS_PLAN_v0.1.json",
        "docs/spec/GENESISBENCH_ANALYSIS_PLAN_v0.1.schema.json",
        "docs/spec/GENESISBENCH_OBSERVATIONS_v0.1.schema.json",
        "docs/spec/GENESISBENCH_ANALYSIS_REPORT_v0.1.schema.json",
        "docs/spec/GC_AGENT_TASK_BENCHMARK_v0.1.schema.json",
        "benchmarks/agent_tasks/v0.1/suite.json",
        "scripts/lib/gc_task_benchmarks.py",
        "benchmarks/genesisbench/v0.1/analysis/observations.fixture.json",
        "benchmarks/genesisbench/v0.1/analysis/report.fixture.json",
        "benchmarks/genesisbench/v0.1/README.md",
        "benchmarks/genesisbench/v0.1/eligibility.fixture.json",
        "benchmarks/genesisbench/v0.1/contamination.fixture.json",
        "examples/agent_benchmark_reproducibility/scaffold-manifest.json",
        "docs/spec/GC_AGENT_BENCHMARK_RUN_v0.1.schema.json",
        "docs/spec/GC_AGENT_HELD_OUT_EVALUATION_v0.1.json",
        "docs/spec/GC_AGENT_HELD_OUT_EVALUATION_v0.1.schema.json",
        "scripts/lib/gc_held_out_evaluation.py",
        "scripts/lib/gc_agent_benchmark_run.py",
        "crates/gc_cli/tests/cli_agent_benchmark_run.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/spec/GC_AGENT_CORPUS_v0.1.json",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/AGENT_ONBOARDING_v0.1.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.md",
        "guides/genesisbench.qmd",
        "guides/index.qmd",
        "README.md",
        "docs/INDEX.md",
        "llms.txt",
        "_quarto.yml",
        "scripts/render_quarto_reference.py",
        "scripts/lib/roadmap_evidence.py",
    ),
    "genesisbench-lineage-analysis-bundle": (
        "docs/spec/GENESISBENCH_ANALYSIS_PLAN_v0.1.json",
        "docs/spec/GENESISBENCH_ANALYSIS_PLAN_v0.1.schema.json",
        "docs/spec/GENESISBENCH_OBSERVATIONS_v0.1.schema.json",
        "docs/spec/GENESISBENCH_ANALYSIS_REPORT_v0.1.schema.json",
        "scripts/lib/genesisbench_analysis.py",
        "benchmarks/genesisbench/v0.1/analysis/observations.fixture.json",
        "benchmarks/genesisbench/v0.1/analysis/report.fixture.json",
        "docs/spec/GC_AGENT_TASK_BENCHMARK_v0.1.schema.json",
        "benchmarks/agent_tasks/v0.1/suite.json",
        "scripts/lib/gc_task_benchmarks.py",
        "docs/spec/GC_AGENT_BENCHMARK_RUN_v0.1.schema.json",
        "scripts/lib/gc_agent_benchmark_run.py",
        "docs/spec/GENESISBENCH_ELIGIBILITY_v0.1.schema.json",
        "scripts/lib/genesisbench_eligibility.py",
        "scripts/lib/genesisbench_protocol.py",
        "scripts/lib/genesisbench_protocol_contract.py",
        "docs/spec/GENESISBENCH_PROTOCOL_v0.1.json",
        "scripts/check_agent_authoring_bundle.sh",
        "crates/gc_cli/tests/cli_agent_task_benchmarks.rs",
        "crates/gc_cli/tests/cli_agent_benchmark_run.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "guides/genesisbench.qmd",
        "README.md",
        "docs/INDEX.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gc-agent-held-out-evaluation-bundle": (
        "docs/spec/GC_AGENT_HELD_OUT_EVALUATION_v0.1.json",
        "docs/spec/GC_AGENT_HELD_OUT_EVALUATION_v0.1.schema.json",
        "docs/spec/GC_AGENT_HELD_OUT_PRIVATE_PACK_v0.1.schema.json",
        "scripts/lib/gc_held_out_evaluation.py",
        "scripts/lib/gc_agent_corpus.py",
        "scripts/check_agent_authoring_bundle.sh",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.md",
        "docs/AGENT_ONBOARDING_v0.1.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "docs/INDEX.md",
        "llms.txt",
        "scripts/lib/roadmap_evidence.py",
    ),
    "genesisbench-temporal-epochs-bundle": (
        "docs/spec/GC_AGENT_HELD_OUT_EVALUATION_v0.1.json",
        "docs/spec/GC_AGENT_HELD_OUT_EVALUATION_v0.1.schema.json",
        "docs/spec/GC_AGENT_HELD_OUT_PRIVATE_PACK_v0.1.schema.json",
        "docs/program/GENESISBENCH_TEMPORAL_EPOCH_AUDIT_v0.1.json",
        "docs/spec/GC_CAPABILITY_LEASE_PROTOCOL_v0.1.json",
        "docs/spec/GC_CAPABILITY_LEASE_PROTOCOL_v0.1.schema.json",
        "scripts/lib/gc_held_out_evaluation.py",
        "scripts/lib/gc_capability_lease.py",
        "scripts/lib/genesisbench_protocol.py",
        "scripts/lib/genesisbench_protocol_contract.py",
        "docs/spec/GENESISBENCH_PROTOCOL_v0.1.json",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "guides/genesisbench.qmd",
        "benchmarks/genesisbench/v0.1/README.md",
        "docs/INDEX.md",
        "README.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "genesisbench-reference-agent-bundle": (
        "benchmarks/genesisbench/v0.1/reference-agent/system.md",
        "benchmarks/genesisbench/v0.1/reference-agent/retrieval.json",
        "benchmarks/genesisbench/v0.1/reference-agent/plan.fixture.json",
        "benchmarks/genesisbench/v0.1/reference-agent/trace.fixture.json",
        "docs/spec/GENESISBENCH_REFERENCE_AGENT_v0.1.json",
        "docs/spec/GENESISBENCH_REFERENCE_AGENT_v0.1.schema.json",
        "docs/spec/GENESISBENCH_REFERENCE_AGENT_ABLATIONS_v0.1.json",
        "docs/spec/GENESISBENCH_REFERENCE_AGENT_ABLATIONS_v0.1.schema.json",
        "docs/spec/GENESISBENCH_REFERENCE_AGENT_TRACE_v0.1.schema.json",
        "scripts/lib/genesisbench_reference_agent.py",
        "scripts/lib/genesisbench_protocol.py",
        "scripts/lib/genesisbench_protocol_contract.py",
        "scripts/lib/genesisbench_tracks.py",
        "docs/spec/GENESISBENCH_PROTOCOL_v0.1.json",
        "docs/spec/GENESISBENCH_PROTOCOL_v0.1.schema.json",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "guides/genesisbench.qmd",
        "benchmarks/genesisbench/v0.1/README.md",
        "docs/spec/GC_AGENT_CORPUS_v0.1.json",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "README.md",
        "docs/INDEX.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "genesisbench-signed-registry-bundle": (
        "docs/spec/GENESISBENCH_REGISTRY_v0.1.json",
        "docs/spec/GENESISBENCH_SUBMISSION_CLAIM_v0.1.schema.json",
        "docs/spec/GENESISBENCH_SIGNED_SUBMISSION_v0.1.schema.json",
        "docs/spec/GENESISBENCH_REGISTRY_POLICY_v0.1.schema.json",
        "docs/spec/GENESISBENCH_REGISTRY_RESULT_v0.1.schema.json",
        "docs/spec/GENESISBENCH_REGISTRY_EVENT_v0.1.schema.json",
        "docs/spec/GENESISBENCH_REGISTRY_CHECKPOINT_v0.1.schema.json",
        "docs/spec/GENESISBENCH_LEADERBOARD_v0.1.schema.json",
        "scripts/lib/genesisbench_registry.py",
        "scripts/lib/genesisbench_front_door.py",
        "scripts/lib/genesisbench_protocol.py",
        "scripts/lib/genesisbench_protocol_contract.py",
        "docs/spec/GENESISBENCH_PROTOCOL_v0.1.json",
        "crates/gc_cli_driver/src/cli_args/command_groups.rs",
        "crates/gc_cli_driver/src/cmd_bench.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "crates/gc_cli/tests/cli_genesisbench_front_door.rs",
        "crates/gc_cli/tests/cli_genesisbench_registry.rs",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/spec/GENESISBENCH_FRONT_DOOR_v0.1.md",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "guides/genesisbench.qmd",
        "benchmarks/genesisbench/v0.1/README.md",
        "docs/spec/GC_AGENT_CORPUS_v0.1.json",
        "README.md",
        "docs/INDEX.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gc-agent-task-cards-bundle": (
        "policies/gc_agent_task_cards_v0.3.json",
        "docs/spec/GC_AGENT_TASK_CARDS_v0.3.md",
        "docs/spec/GC_AGENT_TASK_CARDS_v0.3.json",
        "scripts/lib/gc_agent_task_cards.py",
        "scripts/check_gc_agent_task_cards.sh",
        "scripts/update_gc_agent_task_cards.sh",
        "docs/spec/GC_AGENT_PROFILE_v0.3.json",
        "docs/spec/GC_AGENT_CORE_CARD_v0.3.json",
        "crates/gc_cli_driver/src/cmd_agent_task_cards.rs",
        "crates/gc_cli_driver/src/cmd_agent_plan.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "crates/gc_cli_driver/src/lib.rs",
        "crates/gc_cli/tests/cli_agent_plan.rs",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/AGENT_ONBOARDING_v0.1.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "docs/spec/WRITE_GENESISCODE_SKILL_v0.1.json",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.json",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.md",
        "scripts/check_write_genesiscode_skill_guide.sh",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "policies/gates_v0.1.json",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        ".github/workflows/ci.yml",
        "policies/docs/doc_complexity_budget.toml",
        "docs/spec/DOC_COMPLEXITY_TARGETS_v0.1.md",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "README.md",
        "scripts/check_capability_evidence_ledger_contract.sh",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gc-agent-symbol-index-bundle": (
        "policies/gc_agent_symbol_index_v0.3.json",
        "docs/spec/GC_AGENT_SYMBOL_INDEX_v0.3.schema.json",
        "docs/spec/GC_AGENT_SYMBOL_INDEX_v0.3.json",
        "scripts/lib/gc_agent_symbol_index.py",
        "scripts/check_gc_agent_symbol_index.sh",
        "scripts/update_gc_agent_symbol_index.sh",
        "policies/gc_agent_profile_v0.3.json",
        "docs/spec/GC_AGENT_PROFILE_v0.3.json",
        "crates/gc_cli_driver/src/cli_args.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "crates/gc_cli_driver/src/lib.rs",
        "crates/gc_cli_driver/src/selfhost_frontend.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "scripts/check_agent_authoring_bundle.sh",
        "docs/AGENT_ONBOARDING_v0.1.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "docs/spec/WRITE_GENESISCODE_SKILL_v0.1.json",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.json",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.md",
        "scripts/check_write_genesiscode_skill_guide.sh",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "policies/gates_v0.1.json",
        "scripts/check_green_front_door.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        ".github/workflows/ci.yml",
        "docs/INDEX.md",
        "docs/spec/DOC_TOPOLOGY_v0.1.md",
        "README.md",
        "scripts/check_capability_evidence_ledger_contract.sh",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gc-agent-unsupported-behavior-bundle": (
        "policies/gc_agent_profile_v0.3.json",
        "docs/spec/GC_AGENT_PROFILE_v0.3.schema.json",
        "docs/spec/GC_AGENT_PROFILE_v0.3.json",
        "scripts/lib/gc_agent_profile.py",
        "scripts/check_gc_agent_profile.sh",
        "scripts/update_gc_agent_profile.sh",
        "policies/gc_agent_core_card_v0.3.json",
        "docs/spec/GC_AGENT_CORE_CARD_v0.3.md",
        "docs/spec/GC_AGENT_CORE_CARD_v0.3.json",
        "scripts/lib/gc_agent_core_card.py",
        "scripts/check_gc_agent_core_card.sh",
        "scripts/update_gc_agent_core_card.sh",
        "crates/gc_cli/tests/gc_agent_profile_v03.rs",
        "docs/spec/GC_AGENT_SYMBOL_INDEX_v0.3.schema.json",
        "docs/spec/GC_AGENT_SYMBOL_INDEX_v0.3.json",
        "scripts/lib/gc_agent_symbol_index.py",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/AGENT_ONBOARDING_v0.1.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.md",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "docs/INDEX.md",
        "README.md",
        "scripts/check_capability_evidence_ledger_contract.sh",
        "scripts/lib/roadmap_evidence.py",
    ),
    "gc-diagnostic-catalog-bundle": (
        "policies/gc_diagnostic_catalog_v0.1.json",
        "docs/spec/GC_DIAGNOSTIC_CATALOG_v0.1.schema.json",
        "docs/spec/GC_DIAGNOSTIC_CATALOG_v0.1.json",
        "scripts/lib/gc_diagnostic_catalog.py",
        "scripts/update_gc_diagnostic_catalog.sh",
        "scripts/check_cli_diagnostics_contract.sh",
        "scripts/update_cli_diagnostics_contract_report.sh",
        "scripts/render_cli_diagnostics_contract_report.sh",
        "crates/gc_cli_driver/src/diagnostics.rs",
        "crates/gc_cli_driver/src/diagnostics/human.rs",
        "crates/gc_cli_driver/src/cli_args.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "crates/gc_cli_driver/src/cmd_debug.rs",
        "crates/gc_cli_driver/src/lib.rs",
        "crates/gc_cli/tests/cli_diagnostics_matrix.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "policies/gc_agent_profile_v0.3.json",
        "docs/spec/GC_AGENT_PROFILE_v0.3.json",
        "docs/spec/GC_AGENT_CORE_CARD_v0.3.md",
        "docs/spec/GC_AGENT_CORE_CARD_v0.3.json",
        "docs/spec/GC_AGENT_TASK_CARDS_v0.3.md",
        "docs/spec/GC_AGENT_TASK_CARDS_v0.3.json",
        "docs/spec/GC_AGENT_SYMBOL_INDEX_v0.3.json",
        "docs/spec/CLI_JSON_SCHEMAS_v0.1.md",
        "docs/spec/AGENT_INDEX_v0.1.md",
        "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
        "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
        "docs/AGENT_ONBOARDING_v0.1.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "docs/INDEX.md",
        "README.md",
        "scripts/check_capability_evidence_ledger_contract.sh",
        "scripts/lib/roadmap_evidence.py",
    ),
    "structured-failure-contract-bundle": (
        "docs/spec/GC_FAILURE_CONTEXT_v0.1.schema.json",
        "docs/spec/CLI_JSON_SCHEMAS_v0.1.md",
        "crates/gc_cli_driver/src/structured_failures.rs",
        "crates/gc_cli_driver/src/diagnostics.rs",
        "crates/gc_cli_driver/src/diagnostics/human.rs",
        "crates/gc_cli_driver/src/lib.rs",
        "crates/gc_cli_driver/src/cmd_core.rs",
        "crates/gc_cli_driver/src/cmd_security_ops.rs",
        "crates/gc_cli_driver/src/cmd_pkg.rs",
        "crates/gc_cli_driver/src/cmd_pkg/local_workspace_ops.rs",
        "crates/gc_cli_driver/src/package_obligation_cmds.rs",
        "crates/gc_cli_driver/src/policy_config.rs",
        "crates/gc_cli_driver/src/selfhost_bridge.rs",
        "crates/gc_types/src/lib.rs",
        "crates/gc_types/src/diagnostics.rs",
        "crates/gc_obligations/src/obligations/types_api.rs",
        "crates/gc_cli/tests/cli_diagnostics_matrix.rs",
        "crates/gc_cli/tests/cli_structured_failures.rs",
        "scripts/lib/gc_diagnostic_catalog.py",
        "scripts/check_cli_diagnostics_contract.sh",
        "scripts/render_cli_diagnostics_contract_report.sh",
        "scripts/check_no_user_panics.sh",
        "scripts/lib/roadmap_evidence.py",
    ),
    "guarded-repair-hints-bundle": (
        "policies/gc_diagnostic_catalog_v0.1.json",
        "docs/spec/GC_DIAGNOSTIC_CATALOG_v0.1.schema.json",
        "docs/spec/GC_DIAGNOSTIC_CATALOG_v0.1.json",
        "docs/spec/GC_DIAGNOSTIC_REPAIR_PLAN_v0.1.schema.json",
        "docs/spec/CLI_JSON_SCHEMAS_v0.1.md",
        "crates/gc_cli_driver/src/repair_hints.rs",
        "crates/gc_cli_driver/src/diagnostics.rs",
        "crates/gc_cli_driver/src/diagnostics/human.rs",
        "crates/gc_cli_driver/src/cmd_core.rs",
        "crates/gc_cli_driver/src/lib.rs",
        "crates/gc_cli/tests/cli_diagnostics_matrix.rs",
        "crates/gc_cli/tests/cli_structured_failures.rs",
        "scripts/lib/gc_diagnostic_catalog.py",
        "scripts/check_cli_diagnostics_contract.sh",
        "scripts/render_cli_diagnostics_contract_report.sh",
        "docs/INDEX.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "diagnostic-goldens-bundle": (
        "tests/diagnostics/goldens/v0.1/diagnostics.json",
        "crates/gc_cli/tests/cli_diagnostic_goldens.rs",
        "crates/gc_cli_driver/src/structured_failures.rs",
        "crates/gc_cli_driver/src/diagnostics.rs",
        "crates/gc_cli_driver/src/diagnostics/human.rs",
        "crates/gc_cli_driver/src/cmd_core.rs",
        "scripts/lib/gc_diagnostic_goldens.py",
        "scripts/update_cli_diagnostic_goldens.sh",
        "scripts/check_cli_diagnostics_contract.sh",
        "scripts/render_cli_diagnostics_contract_report.sh",
        "docs/spec/CLI_JSON_SCHEMAS_v0.1.md",
        "docs/INDEX.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "diagnostic-repair-utility-bundle": (
        "policies/gc_repair_utility_v0.1.json",
        "benchmarks/diagnostics/repair_utility/v0.1/workloads.json",
        "benchmarks/diagnostics/repair_utility/v0.1/report.json",
        "docs/spec/GC_REPAIR_UTILITY_REPORT_v0.1.schema.json",
        "tools/genesis-reference-repair-agent.py",
        "scripts/lib/gc_repair_utility_runner.py",
        "scripts/lib/gc_repair_utility.py",
        "scripts/render_gc_repair_utility_report.sh",
        "scripts/update_gc_repair_utility_report.sh",
        "scripts/check_cli_diagnostics_contract.sh",
        "scripts/update_cli_diagnostics_contract_report.sh",
        "docs/spec/CLI_JSON_SCHEMAS_v0.1.md",
        "docs/INDEX.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "human-diagnostic-rendering-bundle": (
        "docs/spec/CLI_JSON_SCHEMAS_v0.1.md",
        "crates/gc_cli_driver/src/diagnostics.rs",
        "crates/gc_cli_driver/src/diagnostics/human.rs",
        "crates/gc_cli_driver/src/lib.rs",
        "crates/gc_cli/tests/cli_human_diagnostics.rs",
        "scripts/check_cli_diagnostics_contract.sh",
        "scripts/render_cli_diagnostics_contract_report.sh",
        "scripts/lib/roadmap_evidence.py",
    ),
    "warm-protocol-bundle": (
        "docs/spec/WARM_PROTOCOL_v0.2.schema.json",
        "docs/spec/CLI_JSON_SCHEMAS_v0.1.md",
        "crates/gc_cli_driver/src/cli_args.rs",
        "crates/gc_cli_driver/src/lib.rs",
        "crates/gc_cli_driver/src/warm_protocol.rs",
        "crates/gc_cli_driver/src/warm_request.rs",
        "crates/gc_cli_driver/src/warm_session.rs",
        "crates/gc_cli_driver/src/warm_session/admission.rs",
        "crates/gc_cli_driver/src/warm_session_config.rs",
        "crates/gc_cli_driver/src/warm_state.rs",
        "crates/gc_cli_driver/src/warm_worker.rs",
        "crates/gc_cli_driver/src/warm_worker_process.rs",
        "crates/gc_cli_driver/src/warm_worker_process/platform.rs",
        "crates/gc_cli_driver/src/warm_workspace.rs",
        "crates/gc_cli_driver/src/warm_session_tests.rs",
        "crates/gc_cli/tests/cli_warm.rs",
        "scripts/lib/warm_protocol_contract.py",
        "scripts/check_warm_protocol_contract.sh",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "policies/gates_v0.1.json",
        "docs/INDEX.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "mcp-interface-bundle": (
        "Cargo.toml",
        "Cargo.lock",
        "crates/gc_cli_driver/Cargo.toml",
        "crates/gc_cli_driver_parity/Cargo.toml",
        "crates/gc_cli_driver/src/cli_args.rs",
        "crates/gc_cli_driver/src/cli_schema.rs",
        "crates/gc_cli_driver/src/lib.rs",
        "crates/gc_cli_driver/src/cmd_source.rs",
        "crates/gc_cli_driver/src/cmd_agent_index.rs",
        "crates/gc_cli_driver/src/cmd_agent_lookup.rs",
        "crates/gc_cli_driver/src/cmd_selfhost_helpers.rs",
        "crates/gc_cli_driver/src/selfhost_frontend.rs",
        "crates/gc_cli_driver/src/warm_request.rs",
        "crates/gc_cli_driver/src/mcp/mod.rs",
        "crates/gc_cli_driver/src/mcp/catalog.rs",
        "crates/gc_cli_driver/src/mcp/resources.rs",
        "crates/gc_cli_driver/src/mcp/session.rs",
        "crates/gc_cli_driver/src/mcp/session/cancellation.rs",
        "crates/gc_cli_driver/src/mcp/session/roots.rs",
        "crates/gc_cli_driver/src/mcp/session/transport.rs",
        "crates/gc_cli_driver/src/mcp/session/wire.rs",
        "crates/gc_cli_driver/src/mcp/session/tests.rs",
        "crates/gc_cli/tests/cli_mcp.rs",
        "crates/gc_cli/tests/cli_cli_schema.rs",
        "crates/gc_cli/tests/cli_agent_index.rs",
        "crates/gc_cli/tests/cli_diagnostics_matrix.rs",
        "crates/gc_cli/tests/cli_json_schema_registry.rs",
        "docs/spec/CLI_JSON_SCHEMAS_v0.1.md",
        "docs/spec/GC_DIAGNOSTIC_CATALOG_v0.1.json",
        "tests/diagnostics/goldens/v0.1/diagnostics.json",
        "benchmarks/diagnostics/repair_utility/v0.1/report.json",
        "policies/gc_diagnostic_catalog_v0.1.json",
        "scripts/lib/warm_protocol_contract.py",
        "scripts/check_warm_protocol_contract.sh",
        "scripts/check_cli_diagnostics_contract.sh",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "policies/gates_v0.1.json",
        "docs/INDEX.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "transactional-agent-session-bundle": (
        "docs/spec/AGENT_TRANSACTION_v0.1.schema.json",
        "docs/spec/CLI_JSON_SCHEMAS_v0.1.md",
        "docs/INDEX.md",
        "crates/gc_cli_driver/src/agent_session.rs",
        "crates/gc_cli_driver/src/agent_session/model.rs",
        "crates/gc_cli_driver/src/agent_session/storage.rs",
        "crates/gc_cli_driver/src/cli_args.rs",
        "crates/gc_cli_driver/src/cli_args/command_groups.rs",
        "crates/gc_cli_driver/src/lib.rs",
        "crates/gc_cli_driver/src/selfhost_frontend.rs",
        "crates/gc_cli_driver/src/mcp/catalog.rs",
        "crates/gc_cli/tests/cli_agent_session.rs",
        "crates/gc_cli/tests/cli_mcp.rs",
        "crates/gc_cli/tests/cli_json_schema_registry.rs",
        "policies/gc_agent_task_cards_v0.3.json",
        "docs/spec/GC_AGENT_TASK_CARDS_v0.3.json",
        "docs/spec/GC_AGENT_TASK_CARDS_v0.3.md",
        ".agents/skills/genesiscode-authoring/SKILL.md",
        "docs/write_genesisCode_skill.md",
        "policies/gc_diagnostic_catalog_v0.1.json",
        "docs/spec/GC_DIAGNOSTIC_CATALOG_v0.1.json",
        "scripts/lib/gc_diagnostic_catalog.py",
        "scripts/lib/warm_protocol_contract.py",
        "scripts/check_warm_protocol_contract.sh",
        "scripts/check_agent_authoring_bundle.sh",
        "scripts/check_cli_diagnostics_contract.sh",
        "scripts/check_write_genesiscode_skill_conformance.sh",
        "scripts/lib/roadmap_evidence.py",
    ),
    "agent-session-resources-bundle": (
        "Cargo.lock",
        "crates/gc_cli_driver/Cargo.toml",
        "crates/gc_cli_driver_parity/Cargo.toml",
        "crates/gc_cli_driver/src/cli_args.rs",
        "crates/gc_cli_driver/src/lib.rs",
        "crates/gc_cli_driver/src/session_resources.rs",
        "crates/gc_cli_driver/src/warm_request.rs",
        "crates/gc_cli_driver/src/warm_session.rs",
        "crates/gc_cli_driver/src/warm_session/admission.rs",
        "crates/gc_cli_driver/src/warm_session_config.rs",
        "crates/gc_cli_driver/src/warm_state.rs",
        "crates/gc_cli_driver/src/warm_worker.rs",
        "crates/gc_cli_driver/src/warm_worker_process.rs",
        "crates/gc_cli_driver/src/warm_worker_process/platform.rs",
        "crates/gc_cli_driver/src/mcp/mod.rs",
        "crates/gc_cli_driver/src/mcp/session.rs",
        "crates/gc_cli_driver/src/mcp/session/cancellation.rs",
        "crates/gc_cli_driver/src/mcp/session/tests.rs",
        "crates/gc_cli_driver/src/mcp/session/transport.rs",
        "crates/gc_cli_driver/src/mcp/session/wire.rs",
        "crates/gc_effects/src/lib.rs",
        "crates/gc_effects/src/runner.rs",
        "crates/gc_effects/src/runner_runtime_budget.rs",
        "crates/gc_cli/tests/cli_warm.rs",
        "crates/gc_cli/tests/cli_mcp.rs",
        "docs/spec/AGENT_SESSION_RESOURCES_v0.1.schema.json",
        "docs/spec/WARM_PROTOCOL_v0.2.schema.json",
        "docs/spec/CLI_JSON_SCHEMAS_v0.1.md",
        "docs/spec/GC_DIAGNOSTIC_CATALOG_v0.1.json",
        "tests/diagnostics/goldens/v0.1/diagnostics.json",
        "benchmarks/diagnostics/repair_utility/v0.1/report.json",
        "scripts/lib/warm_protocol_contract.py",
        "scripts/check_warm_protocol_contract.sh",
        "scripts/check_no_user_panics.sh",
        "scripts/check_cli_diagnostics_contract.sh",
        "docs/INDEX.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "hard-cancellation-bundle": (
        "crates/gc_effects/src/lib.rs",
        "crates/gc_effects/src/runner_process_control.rs",
        "crates/gc_effects/src/runner_host_bridge.rs",
        "crates/gc_effects/src/runner_host_bridge_persistent.rs",
        "crates/gc_effects/src/runner_host_bridge_tests.rs",
        "crates/gc_effects/src/runner_timeout.rs",
        "crates/gc_effects/src/runner_capability_dispatch.rs",
        "crates/gc_effects/src/runner_capability_dispatch/process.rs",
        "crates/gc_effects/tests/host_bridge_fault_injection.rs",
        "docs/spec/CAPS_TOML.md",
        "docs/spec/HOST_BRIDGE_PROTOCOL.md",
        "docs/spec/HOST_ABI.md",
        "scripts/check_host_bridge_fault_injection.sh",
        "scripts/render_host_bridge_fault_injection_report.sh",
        "scripts/update_host_bridge_fault_injection_report.sh",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "policies/gates_v0.1.json",
        "docs/INDEX.md",
        "scripts/lib/roadmap_evidence.py",
    ),
    "test-hermeticity-bundle": (
        "crates/gc_effects/src/runner_process_control.rs",
        "crates/gc_effects/src/runner_host_bridge.rs",
        "crates/gc_effects/src/runner_host_bridge_persistent.rs",
        "crates/gc_effects/src/runner_host_bridge_tests.rs",
        "crates/gc_cli/tests/cli_agent_plan.rs",
        "crates/gc_cli/tests/shell_gate_regressions.rs",
        "scripts/lib/gc_agent_task_cards.py",
        "scripts/check_gc_agent_task_cards.sh",
        "scripts/check_host_bridge_fault_injection.sh",
        "scripts/render_host_bridge_fault_injection_report.sh",
        "scripts/check_test_execution_profile_matrix.sh",
        "docs/spec/GC_AGENT_TASK_CARDS_v0.3.json",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        "policies/check_update_boundary_v0.1.json",
        "docs/spec/CHECK_UPDATE_BOUNDARY_AUDIT_v0.1.json",
        "policies/gates_v0.1.json",
        "scripts/lib/roadmap_evidence.py",
    ),
    "warning-free-workspace-bundle": (
        "crates/gc_cli_driver/src/mcp/catalog.rs",
        "crates/gc_cli_driver/src/mcp/session.rs",
        "crates/gc_cli_driver/src/mcp/session/transport.rs",
        "crates/gc_cli_driver/src/mcp/mod.rs",
        "crates/gc_cli_driver/src/warm_session.rs",
        "crates/gc_cli_driver/src/warm_session/admission.rs",
        "crates/gc_cli_driver/src/warm_session_config.rs",
        "crates/gc_cli_driver/src/warm_worker_process.rs",
        "crates/gc_cli_driver/src/warm_worker_process/platform.rs",
        "crates/gc_cli_driver/src/program_builders/pkg.rs",
        "crates/gc_cli_driver/src/pkg_reports.rs",
        "crates/gc_cli_driver/src/cmd_pkg/frontend_dispatch/rust.rs",
        "crates/gc_cli_driver/src/cmd_pkg/frontend_dispatch/selfhost.rs",
        "crates/gc_cli/tests/cli_pkg_workspace.rs",
        "scripts/lib/lint_suppression_policy.py",
        "scripts/check_test_execution_profile_matrix.sh",
        "scripts/render_runtime_backend_feature_matrix_report.sh",
        "scripts/check_runtime_backend_feature_matrix.sh",
        "scripts/render_upgrade_plan_health_report.sh",
        "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
        ".github/workflows/ci.yml",
        "scripts/lib/roadmap_evidence.py",
    ),
}

CARGO_CACHE_AUTHORITY_FILES = (
    "policies/cargo_cache_v0.1.json",
    "docs/spec/CARGO_CACHE_POLICY_v0.1.schema.json",
    "scripts/lib/cargo_cache.py",
    "scripts/lib/cargo_target_dir.sh",
    "scripts/lib/generated_state.py",
    "scripts/check_cargo_target_dir_policy.sh",
    "scripts/check_evidence_storage_classes.sh",
    "scripts/render_cargo_target_dir_policy_report.sh",
    "scripts/render_evidence_release_asset.sh",
    ".github/workflows/ci.yml",
    "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
    "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
)

CHANGED_IMPACT_AUTHORITY_FILES = (
    "policies/changed_impact_v0.1.json",
    "docs/spec/CHANGED_IMPACT_POLICY_v0.1.schema.json",
    "scripts/lib/changed_impact.py",
    "scripts/check_changed_impact.sh",
    "scripts/test_changed_fast.sh",
    "docs/spec/CHECK_UPDATE_BOUNDARY_v0.1.md",
    "docs/spec/TEST_EXECUTION_PROFILES_v0.1.md",
    ".github/workflows/ci.yml",
)

BUNDLE_OCCURRENCES = {
    "capability-ledger-bundle": 2,
    "status-authority-bundle": 2,
    "root-lock-policy-bundle": 1,
    "roadmap-execution-contract-bundle": 1,
    "genesis-evidence-profile-bundle": 1,
    "genesis-evidence-verifier-bundle": 1,
    "evidence-storage-classes-bundle": 1,
    "evidence-adversarial-matrix-bundle": 2,
    "prerequisite-manifest-bundle": 1,
    "dependency-mirror-bundle": 1,
    "version-surface-bundle": 1,
    "v1-compatibility-registry-bundle": 1,
    "gate-manifest-bundle": 1,
    "cargo-cache-bundle": 1,
    "changed-impact-bundle": 1,
    "gate-resource-telemetry-bundle": 1,
    "deterministic-cleanup-bundle": 1,
    "generated-state-lifecycle-bundle": 1,
    "governance-consolidation-bundle": 1,
    "engineering-gate-budget-bundle": 1,
    "reference-host-profile-bundle": 1,
    "roadmap-workload-bundle": 1,
    "roadmap-baseline-bundle": 1,
    "release-notes-bundle": 1,
    "gc-agent-profile-bundle": 1,
    "gc-agent-core-card-bundle": 1,
    "gc-agent-corpus-bundle": 1,
    "gc-canonical-examples-bundle": 1,
    "gc-agent-task-benchmark-bundle": 1,
    "gc-agent-benchmark-scoring-bundle": 1,
    "gc-agent-benchmark-run-bundle": 1,
    "genesisbench-protocol-bundle": 2,
    "genesisbench-lineage-analysis-bundle": 1,
    "gc-agent-held-out-evaluation-bundle": 1,
    "genesisbench-temporal-epochs-bundle": 1,
    "genesisbench-reference-agent-bundle": 1,
    "genesisbench-signed-registry-bundle": 1,
    "gc-agent-task-cards-bundle": 1,
    "gc-agent-symbol-index-bundle": 1,
    "gc-agent-unsupported-behavior-bundle": 1,
    "gc-diagnostic-catalog-bundle": 1,
    "structured-failure-contract-bundle": 1,
    "guarded-repair-hints-bundle": 1,
    "diagnostic-goldens-bundle": 1,
    "diagnostic-repair-utility-bundle": 1,
    "human-diagnostic-rendering-bundle": 1,
    "warm-protocol-bundle": 1,
    "mcp-interface-bundle": 1,
    "transactional-agent-session-bundle": 1,
    "agent-session-resources-bundle": 1,
    "hard-cancellation-bundle": 1,
    "test-hermeticity-bundle": 1,
    "warning-free-workspace-bundle": 1,
}


class EvidenceError(ValueError):
    pass


def bundle_digest(paths: Sequence[str]) -> str:
    digest = sha256()
    for rel in paths:
        path = ROOT / rel
        if not path.is_file():
            raise EvidenceError(f"missing bundle input: {rel}")
        rel_bytes = rel.encode("utf-8")
        content = path.read_bytes()
        digest.update(len(rel_bytes).to_bytes(8, "big"))
        digest.update(rel_bytes)
        digest.update(len(content).to_bytes(8, "big"))
        digest.update(content)
    return digest.hexdigest()


def authority_bundle_digest(paths: Sequence[str]) -> str:
    identity = [
        {"path": rel, "sha256": sha256((ROOT / rel).read_bytes()).hexdigest()}
        for rel in sorted(paths)
    ]
    canonical = json.dumps(identity, sort_keys=True, separators=(",", ":")) + "\n"
    return sha256(canonical.encode("utf-8")).hexdigest()


def cargo_cache_authority_files() -> Sequence[str]:
    paths = set(CARGO_CACHE_AUTHORITY_FILES)
    cargo_re = re.compile(r"(^|[ \t])cargo[ \t]+", re.MULTILINE)
    excluded = {"check_test_execution_profile_matrix.sh", "render_cargo_target_dir_policy_report.sh"}
    for path in sorted((ROOT / "scripts").glob("*.sh")):
        text = path.read_text(encoding="utf-8")
        if path.name not in excluded and (
            "genesis_configure_cargo_target_dir" in text or cargo_re.search(text)
        ):
            paths.add(path.relative_to(ROOT).as_posix())
    return tuple(sorted(paths))


def identities() -> Mapping[str, str]:
    result = {name: bundle_digest(paths) for name, paths in BUNDLES.items()}
    result["cargo-cache-bundle"] = authority_bundle_digest(cargo_cache_authority_files())
    result["changed-impact-bundle"] = authority_bundle_digest(CHANGED_IMPACT_AUTHORITY_FILES)
    return result


def check_roadmap(path: Path) -> None:
    if not path.is_file():
        raise EvidenceError(f"missing roadmap: {path}")
    text = path.read_text(encoding="utf-8")
    rendered = identities()
    cited_names = set(re.findall(r"([a-z0-9-]+-bundle)-sha256:[0-9a-f]{64}", text))
    unknown = sorted(cited_names - set(rendered))
    if unknown:
        raise EvidenceError(f"unregistered roadmap evidence bundle(s): {unknown}")
    for name, digest in rendered.items():
        pattern = re.compile(rf"{re.escape(name)}-sha256:([0-9a-f]{{64}})")
        observed = pattern.findall(text)
        expected_occurrences = BUNDLE_OCCURRENCES[name]
        if len(observed) != expected_occurrences:
            raise EvidenceError(
                f"{name} identity must occur exactly {expected_occurrences} time(s) in "
                f"ROADMAP.md; observed={len(observed)}"
            )
        stale = sorted(set(observed) - {digest})
        if stale:
            raise EvidenceError(
                f"{name} identity drift: expected={digest} observed={sorted(set(observed))}"
            )


def main(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--print", dest="print_identities", action="store_true")
    parser.add_argument("--roadmap", type=Path, default=DEFAULT_ROADMAP)
    args = parser.parse_args(argv)
    try:
        if args.check:
            check_roadmap(args.roadmap.resolve())
            rendered = identities()
            print(
                "roadmap-evidence-identities: ok "
                + " ".join(f"{name}={digest}" for name, digest in rendered.items())
            )
        else:
            for name, digest in identities().items():
                print(f"{name}-sha256:{digest}")
    except EvidenceError as exc:
        print(f"roadmap-evidence-identities: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
