#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/gate_telemetry.sh"
genesis_gate_telemetry_reexec "$0" "$@"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

GUIDE="docs/write_genesisCode_skill.md"
[[ -f "$GUIDE" ]] || {
  echo "write-genesiscode-skill-guide: missing guide: $GUIDE" >&2
  exit 1
}

python3 - "$GUIDE" <<'PY'
import pathlib
import re
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text(encoding="utf-8")

required_refs = [
    ".agents/skills/genesiscode-authoring/SKILL.md",
    "docs/spec/AGENT_AUTHORING_BUNDLE_v0.1.md",
    "docs/spec/GC_AGENT_CORE_CARD_v0.3.md",
    "docs/spec/GC_AGENT_PROFILE_v0.3.json",
    "docs/spec/GC_AGENT_TASK_CARDS_v0.3.json",
    "docs/spec/GC_AGENT_SYMBOL_INDEX_v0.3.json",
    "docs/spec/WRITE_GENESISCODE_SKILL_v0.1.json",
    "docs/spec/WRITE_GENESISCODE_SKILL_PACK_v0.1.md",
    "docs/spec/WRITE_GENESISCODE_SKILL_DISTRIBUTION_v1.md",
    "docs/skill_pack/write_genesiscode_v1/prompt-cards.json",
    "docs/skill_pack/write_genesiscode_v1/recipe-cards.json",
]
missing_refs = [r for r in required_refs if r not in text]
if missing_refs:
    raise SystemExit(
        "write-genesiscode-skill-guide: missing canonical reference(s): " + ", ".join(missing_refs)
    )

if "/Users/" in text:
    raise SystemExit(
        "write-genesiscode-skill-guide: canonical references must be repository-relative"
    )

numbered = re.findall(r"^\d+\. ", text, flags=re.MULTILINE)
if len(numbered) < 5:
    raise SystemExit("write-genesiscode-skill-guide: expected five onboarding steps")

if "Generated by scripts/lib/genesiscode_authoring_skill.py" not in text or "policy-sha256:" not in text:
    raise SystemExit("write-genesiscode-skill-guide: generated provenance marker missing")

print(
    "write-genesiscode-skill-guide: ok "
    f"(steps={len(numbered)} refs={len(required_refs)})"
)
PY
