use super::*;
use gc_coreform::{hash_term, print_term};
use num_bigint::BigInt;
use std::collections::{BTreeMap, BTreeSet};

fn limits() -> RuntimeTermHashLimits {
    RuntimeTermHashLimits {
        max_nodes: 200_001,
        max_encoded_bytes: 2_000_000,
        max_pending_frames: 30_001,
    }
}
fn pair(car: i64, cdr: i64) -> Term {
    Term::Pair(
        Box::new(Term::Int(car.into())),
        Box::new(Term::Int(cdr.into())),
    )
}
fn hex(hash: [u8; 32]) -> String {
    hash.iter().map(|byte| format!("{byte:02x}")).collect()
}

#[test]
fn structural_term_hash_matches_independent_all_tag_vectors() {
    // Frozen Python encoder + pinned python-blake3 1.0.4 vectors, not generated by this codec.
    let cases = vec![
        (
            "nil",
            Term::Nil,
            "f4c11e50a6146bc53c12aebb3c94a922faae7ad5f87ef2bedf1d06f9e2e22622",
        ),
        (
            "false",
            Term::Bool(false),
            "730bc0c5cb72467129b0fb1b8cddf63a638a3fd5ea443c0c96e47c14f699fe3a",
        ),
        (
            "true",
            Term::Bool(true),
            "dd1f0625fccf1a3b94b7e4c3206a1b6dd130314032aedfcedca64215ce16beaf",
        ),
        (
            "zero",
            Term::Int(0.into()),
            "8b95e11f98c51959be3f7c954ade2cd2e643e2a9b2b09686be362070e7d159f7",
        ),
        (
            "one",
            Term::Int(1.into()),
            "2a5cf0323f22a2df61357cd909cef40bd65faca8dc590513947288737cf7cea4",
        ),
        (
            "negative-one",
            Term::Int((-1).into()),
            "07764f2882fcdf9c0ab4b9d4db71e6fc8b82b2e2e92ae6a8855fdafea39aa817",
        ),
        (
            "large-positive",
            Term::Int((BigInt::from(1_u8) << 64_usize) + 9_u8),
            "f14d93d434f01f29dfcb9914e12eb07974a2e3cece12dc99b721935c67747f59",
        ),
        (
            "large-negative",
            Term::Int(-((BigInt::from(1_u8) << 64_usize) + 9_u8)),
            "ee358c7b8de6bb19940f460441c23cdecaf4d26f89dd2d509789d248da1c70de",
        ),
        (
            "unicode-text",
            Term::Str("é🙂\0".into()),
            "c641614b07fa39933ef3289ee265d0b27e403a8189841a299490e7f4763db313",
        ),
        (
            "octets",
            Term::Bytes(vec![0, 255, 128].into()),
            "4a2f12d780cf01aefb0e6a0ceaac1116ce36e70c65b99026024adba8d72f4398",
        ),
        (
            "raw-reserved-symbol",
            Term::Symbol("true".into()),
            "c322e75a718da4dc818fbdd17e7b34dc9ad5881dec4f86f195b4a45afb511a7e",
        ),
        (
            "raw-nul-symbol",
            Term::Symbol("a\0b".into()),
            "79a31edad4b990bc60172983f08985d05d717997491268244153ca041e7e0752",
        ),
        (
            "pair-1-2",
            pair(1, 2),
            "2a72fc945aa5002bae2c488188a324c0e1d4b3603aeea16d8e9234ed468fb202",
        ),
        (
            "pair-3-4",
            pair(3, 4),
            "961326bb688e570cb74dc332c00d32abe9ba6b32e49160da60fcad457761f668",
        ),
        (
            "proper-placeholder",
            Term::list(vec![
                Term::Symbol("pair".into()),
                Term::Symbol("<improper>".into()),
            ]),
            "173d61a48daeb764614415780ec21c09d69add6d268aec3f8d87f69652227083",
        ),
        (
            "empty-vector",
            Term::Vector(vec![]),
            "b1677be68fc50f089bb18d5dfb79164f9ffa23de3ce69ad6bd9f03a23326dba7",
        ),
        (
            "nested-vector",
            Term::Vector(vec![Term::Nil, pair(1, 2)]),
            "cf3b1f579a9557193ea875e51fdd95b689914204d0df574f90510982019553e1",
        ),
        (
            "empty-map",
            Term::Map(BTreeMap::new()),
            "c752c761327ba8cc9576d7026a022358d61bf096307e6a202ade63b11461449e",
        ),
        (
            "nested-map",
            Term::Map(
                [
                    (TermOrdKey(Term::Symbol(":a".into())), pair(1, 2)),
                    (
                        TermOrdKey(pair(3, 4)),
                        Term::Vector(vec![Term::Int((-1).into()), Term::Str("é".into())]),
                    ),
                ]
                .into(),
            ),
            "9e40ec479a75b92209eac3add047e26ca635c4228a70c50c5d604e68f36664c7",
        ),
    ];
    let mut seen = BTreeSet::new();
    for (name, term, expected) in cases {
        let observed = hex(runtime_term_hash(&term, limits()).unwrap());
        assert_eq!(observed, expected, "{name}");
        assert!(
            seen.insert(observed),
            "fixture aliases another distinct term: {name}"
        );
    }
}

#[test]
fn structural_term_hash_separates_nested_improper_and_raw_symbol_aliases() {
    let mut terms = vec![
        Term::Nil,
        Term::Symbol("nil".into()),
        Term::Bool(true),
        Term::Symbol("true".into()),
        Term::Int(1.into()),
        Term::Symbol("1".into()),
        Term::Str("x".into()),
        Term::Symbol("x".into()),
        Term::Bytes(b"x".to_vec().into()),
        Term::list(vec![
            Term::Symbol("pair".into()),
            Term::Symbol("<improper>".into()),
        ]),
    ];
    for number in -16..16 {
        terms.push(pair(number, number + 1));
    }
    let mut hashes = BTreeMap::new();
    for term in terms {
        for nested in [
            term.clone(),
            Term::Vector(vec![term.clone()]),
            Term::Map([(TermOrdKey(Term::Nil), term.clone())].into()),
            Term::Map([(TermOrdKey(term), Term::Nil)].into()),
        ] {
            let hash = runtime_term_hash(&nested, limits()).unwrap();
            if let Some(previous) = hashes.insert(hash, nested.clone()) {
                assert_eq!(previous, nested, "unequal structural terms aliased");
            }
        }
    }
    assert_eq!(hashes.len(), 167);
}

#[test]
fn structural_term_hash_does_not_change_canonical_store_or_legacy_value_identity() {
    let proper = Term::list(vec![
        Term::Symbol("pair".into()),
        Term::Symbol("<improper>".into()),
    ]);
    assert_eq!(print_term(&proper), "(pair <improper>)");
    // A frozen existing v0.2 canonical hash; the additive profile cannot replace it.
    assert_eq!(
        hex(hash_term(&proper)),
        "59564e4d8fcafbd06c06a5f54deefc6969cdd72861eb7ee50da1fd5c9c4bc9c9"
    );
    assert_eq!(
        hex(crate::value_hash(&crate::Value::data(proper))),
        "b9ad37409e134445e770a816fd877728d009267997f0eb8fd926cd40e09ced02"
    );
    assert_eq!(
        crate::VALUE_EFFECT_HASH_PROFILE_ID,
        "genesis/value-effect-hash/v0.2"
    );
    assert_eq!(
        RUNTIME_TERM_HASH_PROFILE_ID,
        "genesis/runtime-term-hash/v0.3"
    );
}

#[test]
fn structural_term_hash_limits_are_exact_and_fail_with_typed_dimensions() {
    let term = Term::Vector(vec![Term::Bool(false), Term::Nil]);
    let bytes = DOMAIN.len() as u64 + 9 + 2 + 1;
    let exact = RuntimeTermHashLimits {
        max_nodes: 3,
        max_encoded_bytes: bytes,
        max_pending_frames: 2,
    };
    runtime_term_hash(&term, exact).unwrap();
    for (short, dimension, observed, limit) in [
        (
            RuntimeTermHashLimits {
                max_nodes: 2,
                ..exact
            },
            "runtime-hash-nodes",
            3,
            2,
        ),
        (
            RuntimeTermHashLimits {
                max_encoded_bytes: bytes - 1,
                ..exact
            },
            "runtime-hash-bytes",
            bytes,
            bytes - 1,
        ),
        (
            RuntimeTermHashLimits {
                max_pending_frames: 1,
                ..exact
            },
            "runtime-hash-frames",
            2,
            1,
        ),
        (
            RuntimeTermHashLimits {
                max_pending_frames: 0,
                ..exact
            },
            "runtime-hash-frames",
            1,
            0,
        ),
        (
            RuntimeTermHashLimits {
                max_nodes: 0,
                ..exact
            },
            "runtime-hash-nodes",
            1,
            0,
        ),
        (
            RuntimeTermHashLimits {
                max_encoded_bytes: 0,
                ..exact
            },
            "runtime-hash-bytes",
            DOMAIN.len() as u64,
            0,
        ),
    ] {
        let error = runtime_term_hash(&term, short).unwrap_err();
        assert!(matches!(error.kind, KernelErrorKind::MemoryLimit));
        assert_eq!(
            error.resource_limit.unwrap(),
            crate::ResourceLimit {
                dimension,
                observed,
                limit
            }
        );
    }
    let huge_integer = Term::Int(BigInt::from(1_u8) << 32768);
    let error = runtime_term_hash(
        &huge_integer,
        RuntimeTermHashLimits {
            max_encoded_bytes: DOMAIN.len() as u64 + 10,
            ..limits()
        },
    )
    .unwrap_err();
    assert_eq!(
        error.resource_limit.unwrap().dimension,
        "runtime-hash-bytes"
    );
    let huge_blob = Term::Bytes(vec![42; 1_000_000].into());
    let error = runtime_term_hash(
        &huge_blob,
        RuntimeTermHashLimits {
            max_encoded_bytes: DOMAIN.len() as u64 + 9,
            ..limits()
        },
    )
    .unwrap_err();
    assert_eq!(
        error.resource_limit.unwrap().observed,
        DOMAIN.len() as u64 + 9 + 1_000_000
    );
}

fn dismantle_pair(mut term: Term) {
    // Term's own destructor is a separate boundary; do not make it this hash test's stack limit.
    while let Term::Pair(car, cdr) = term {
        assert_eq!(*cdr, Term::Nil);
        term = *car;
    }
}

#[test]
fn structural_term_hash_streams_deep_and_wide_without_host_recursion_or_fanout_stack() {
    std::thread::Builder::new()
        .stack_size(96 * 1024)
        .spawn(|| {
            let mut term = Term::Nil;
            for _ in 0..20_000 {
                term = Term::Pair(Box::new(term), Box::new(Term::Nil));
            }
            let result = runtime_term_hash(&term, limits());
            let bounded = runtime_term_hash(
                &term,
                RuntimeTermHashLimits {
                    max_pending_frames: 16,
                    ..limits()
                },
            );
            dismantle_pair(term);
            result.unwrap();
            assert_eq!(
                bounded.unwrap_err().resource_limit.unwrap().dimension,
                "runtime-hash-frames"
            );
        })
        .unwrap()
        .join()
        .unwrap();
    let wide = Term::Vector(vec![Term::Nil; 100_000]);
    runtime_term_hash(
        &wide,
        RuntimeTermHashLimits {
            max_pending_frames: 2,
            ..limits()
        },
    )
    .unwrap();
    let map = Term::Map(
        (0..10_000)
            .map(|n| (TermOrdKey(Term::Int(n.into())), Term::Nil))
            .collect(),
    );
    runtime_term_hash(
        &map,
        RuntimeTermHashLimits {
            max_pending_frames: 3,
            ..limits()
        },
    )
    .unwrap();
}

#[test]
fn structural_term_hash_map_identity_preserves_canonical_key_order() {
    let forward: BTreeMap<_, _> = (0..64)
        .map(|n| (TermOrdKey(pair(n, n + 1)), Term::Str(n.to_string())))
        .collect();
    let backward: BTreeMap<_, _> = (0..64)
        .rev()
        .map(|n| (TermOrdKey(pair(n, n + 1)), Term::Str(n.to_string())))
        .collect();
    assert_eq!(
        runtime_term_hash(&Term::Map(forward), limits()).unwrap(),
        runtime_term_hash(&Term::Map(backward), limits()).unwrap()
    );
}

#[test]
fn structural_term_hash_counter_overflow_is_an_explicit_error_at_maximum_limits() {
    let mut encoder = Encoder {
        hasher: Hasher::new(),
        limits: RuntimeTermHashLimits {
            max_nodes: u64::MAX,
            max_encoded_bytes: u64::MAX,
            max_pending_frames: usize::MAX,
        },
        nodes: u64::MAX,
        bytes: u64::MAX,
    };
    for error in [
        encoder.node().unwrap_err(),
        encoder.charge_bytes(1).unwrap_err(),
    ] {
        assert!(matches!(error.kind, KernelErrorKind::MemoryLimit));
        assert!(
            error.resource_limit.is_none(),
            "overflow has no representable exact observation"
        );
    }
}
